### PR TITLE
Fix GeoIP to use correct databases

### PR DESCRIPTION
**Pull request by recrudesce**
Fixes https://github.com/dtag-dev-sec/PEBA/issues/48

Downloads and uses correct GeoLite2 databases.

### CODE REVIEW

**Comment by vorband** [comment]
it won't work out of the box as we have to switch to geoip2 in the processing as well. 
I will fix this asap and come up with a solution. Thanks.

**Comment by recrudesce** [comment]
It worked fine for me (my instance is geoip'ing fine) - all I did was edit the download script and then edited the python script to use the mmdb's as per this.  Makes sense to use the proper geoip2 library, I agree :)

**Comment by vorband** [comment]
Unfortunately, this did not work for me. So, I decided to replace the pygeoip with the official geoip2 module and clean up the code. It seems to be working. Just need to test it a little more before I commit.  Again, thank you! :)

**Comment by vorband** [comment]
I have implemented it in the devbackup branch https://github.com/dtag-dev-sec/PEBA/commit/47cb7f2b1fb3136aa47b280f885963234449432c and will merge it into master as soon as I know it runs stable.

**Comment by vorband** [comment]
closing this now. thanks.

**Comment by vorband** [comment]
merged into master branch

**Pull request closed without merging**
